### ISSUE TITLE
BIDS compatibility and zapline for cleaning line noise

### ISSUE THREAD

**Issue by cmmrandau** [NeilwBailey/RELAX#1]
Dear developers of RELAX,

your pipeline is much appreciated! I am hoping to switch to RELAX from my current ICA/IClabel approach, which requires me to choose a set of more or less arbitrary variables (e.g. what % to include for brain artifacts). I am especially happy that RELAX filters at 0.25 Hz for ERP analysis, instead of the 1 Hz "required"  for ICA.

I have, however, two ideas which would further improve the usability of RELAX: 

1. Include an option to export the processed files to a BIDS-compatible format (https://www.nature.com/articles/s41597-019-0104-8). This function already exists in EEGLAB (https://github.com/sccn/bids-matlab-tools) and would allow for seamless further processing in e.g. LIMO (https://github.com/LIMO-EEG-Toolbox/limo_tools).

2. Include an option to use the newly developed tool zapline (https://pubmed.ncbi.nlm.nih.gov/35278015/ and https://github.com/MariusKlug/zapline-plus) to remove line noise. My experience is that zapline is vastly superior to clean_line used in PREP, and manages to completely remove all line noise. I would also prefer not to use a notch filter, which is the method used in RELAX. 

Best wishes,
Martin
M.D., Phd-student

**Comment by NeilwBailey** [comment]
Dear Martin

Thank you for the suggestions. We have now provided the potential to implement zapline plus as a method to remove line noise rather than simply Butterworth notch filtering. This is provided in a beta version, so that users can still use the original version which has been formally tested (in contrast to the beta version, which has just informally been tested).

Unfortunately we do not have the time to provide the BIDS-compatible option at this stage. Since the function already exists in EEGLAB, hopefully it's not too much trouble to code exporting the files in this format yourself, and we hope to provide this option in the future.
