### ISSUE TITLE
Error in RELAX_drift

### ISSUE THREAD

**Issue by izzycourtney26** [NeilwBailey/RELAX#17]
Hello,

I'm currently trying to implement RELAX to process data from a go-nogo experiment. RELAX ran for 60 out of 70 of the data files, but for the other 10, this error keeps happening:

Attempt to grow array along ambiguous dimension.

Error in RELAX_drift (line 145)
                CumulativeExceedsUpperBoundPerEpoch(1,e)=NaN;

Error in RELAX_Wrapper_beta (line 425)
        [continuousEEG, epochedEEG] = RELAX_drift(continuousEEG, epochedEEG, RELAX_cfg); %
        Use epoched data to add periods showing excessive drift to the mask

Error in pop_RELAX_beta (line 600)
        RELAXProcessing_ICA_AllParticipants, RELAXProcessingRoundThreeAllParticipants,
        RELAX_issues_to_check, RELAXProcessingExtremeRejectionsAllParticipants] =
        RELAX_Wrapper_beta (RELAX_cfg);

All of our data is pretty noisy, including the ones that RELAX crashed on, but they don't seem that much noisier than the others. Any advice would be much appreciated!

**Comment by NeilwBailey** [comment]
Hi there

I haven't seen that error before, so I don't have a ready-made solution
sorry.

I would recommend saving the pre-processing steps for one of the files
causing the issue (which will save the data just prior to this error), then
sequentially applying the functions in RELAX_Wrapper_beta that occur after
the blink cleaning to that saved file until RELAX_drift. Then applying the
code within RELAX_drift to the file showing the error until the line that
causes the error. Then inspect the relevant variables in the workspace.

It looks like there might be a size mismatch between the following two
variables: epochedEEG.RELAX.EpochsMarkedAsNaNsForExtremeEvents and
CumulativeExceedsUpperBoundPerEpoch.
Although I'm not sure why that might occur. Hopefully inspection of the
variables and code leading up to the error will help. If you follow these
steps and gain a helpful insight, but still haven't managed to solve the
problem, let me know and I might be able to help further.

Otherwise, if your study design allows it, you could set a higher high-pass
filter for all your data (1Hz would likely take care of the drift that is
causing the issue). Alternatively, the error seems to be occurring in the
lead-up to the MWF cleaning. If the wICA_ICLabel setting provides
sufficient cleaning by itself, you could consider only applying that
cleaning (in reasonably clean data, I think wICA_ICLabel might be the
preferred method. Although it leaves more artifacts in the data, that cost
might be more than offset by a better preservation of signal). This
wouldn't resolve the problem, but instead might by-pass it so that you
don't need to solve it (while still providing sufficient data
pre-processing if your experimental design allows for these settings).

Kind regards,

Neil

**Comment by izzycourtney26** [comment]
Thanks! I stepped through the RELAX_Wrapper function and saw that for those subjects, after the call to RELAX_epoching in line 393, the size of epochedEEG.RELAX.EpochsMarkedAsNaNsForExtremeEvents was bigger than the number of epochs in epochedEEG. I was able to resolve the issue by setting OnlyIncludeTaskRelatedEpochs to 0 instead of 1.

**Comment by NeilwBailey** [comment]
Great to hear you were able to resolve the issue, thank you for letting me know.
