### ISSUE TITLE
error "NoiseMaskFullLength" using RestingState Data without MWF

### ISSUE THREAD

**Issue by jbellwickes** [NeilwBailey/RELAX#18]
Kia Ora, Neil

Posting this question up here so others can benefit from your time/feedback!

I also seem to be getting the following error for certain participants whenever I run the RELAX_beta pre-processing script without MWF on my resting state data:

"Reference to non-existent field 'NoiseMaskFullLength'.

Error in RELAX_horizontaleye (line 294)
            for e=1:size(continuousEEG.RELAXProcessing.Details.NoiseMaskFullLength,2)

Error in RELAX_Wrapper_beta (line 246)
        [Marking_artifacts_for_SER_ARR] = RELAX_horizontaleye(continuousEEG, RELAX_cfg);

Error in RELAX_beta_params (line 390)
        RELAXProcessing_ICA_AllParticipants, RELAXProcessingRoundThreeAllParticipants, RELAX_issues_to_check,
        RELAXProcessingExtremeRejectionsAllParticipants] = RELAX_Wrapper_beta (RELAX_cfg);"
 
I've had a read through of the previous report of a similar issue posted here but I wasn't able to find a solution. 
The same participants data for the eyes closed breathing counting task and sternberg task was processed without any issues and the data was cleaned nicely. I have tried cleaning the resting state data with the MWF as well but the cleaned data ends up containing excessive noise and the participant is rejected entirely using the RELAX_epoch cleaning step. 

I've included a zip file with the parameter settings and an example participant where I get the error. 
[RELAX_issue.zip](https://github.com/NeilwBailey/RELAX/files/14972470/RELAX_issue.zip)

Thank you so much in advance!

**Comment by NeilwBailey** [comment]
Hi there

I'm struggling for time a bit at the moment, so unfortunately might not be able to troubleshoot this in detail until next week. But a quick potential solution in the meantime might be to de-select the metric outputs when you're using RELAX to clean this participant's data (which I think will tell RELAX to skip the section that is causing the problem).

Hopefully that works, and I hope to provide a more complete solution next week sometime.

Kind regards,

Neil

**Comment by NeilwBailey** [comment]
Hi Jodie

Sorry about my slow reply here, it's been a busy month. Hopefully the stop-gap solution I mentioned in my previous comment worked for the time being?

Unfortunately, I wasn't able to replicate the issue you reported for that file - RELAX pre-processed it without any issues on my system, even using the exact settings you provided. The only thing I can think of to check is that you're using RELAX_v1.1.5?

Otherwise, inserting the following line of code into RELAX_excluding_extreme_values.m immediately after line 246 might solve the issue (although it's hard for me to know for sure without being able to reproduce the issue myself):

epochedEEG.RELAXProcessing.Details.NoiseMaskFullLength=epochedEEG.RELAXProcessing.Details.NaNsForNonEvents;

Please let me know if this does (or does not) solve the issue, and I might be able to help further.

Kind regards,

Neil

**Comment by NeilwBailey** [comment]
Just noting here that I have been informed by Jodie that the solution mentioned above works. This solution will be implemented in the next version of RELAX, which will be provided in an update shortly.
