### ISSUE TITLE
MaxProportionOfMuscleEpochsToClean not working?

### ISSUE THREAD

**Issue by cmmrandau** [NeilwBailey/RELAX#2]
It seems that changing the values of RELAX_epoching_cfg.MaxProportionOfMuscleEpochsToClean=0.20 does not have an effect. It still defaults to 0.5. I might be missing something...

BW
Martin

**Comment by NeilwBailey** [comment]
Dear Martin

Thank you for noting this issue. There was an inconsistency between the variable name used in the Wrapper / GUI and the variable name used in the RELAX_Rejecting_muscle_epochs.m script, so the lower level script was just using the default setting rather than using the user setting. This has now been fixed in v1.1.0.

Kind regards,

Neil
