### ISSUE TITLE
Unrecognised function or variable "BlinkIndexMetric"

### ISSUE THREAD

**Issue by mitanshu7** [NeilwBailey/RELAX#20]
I am having an issue with the following error.

![image](https://github.com/user-attachments/assets/aae189cb-2cfb-4833-8cf5-10673d56f9d9)

I also tried the option for - 6Hz low pass filter before blink detection - rather unsuccessfully. 

I appreciate any help possible!

Thank you in advance.

Some helpful stats:
```
EEGLAB: adding "ICLabel" v1.6 (see >> help eegplugin_iclabel)
EEGLAB: adding "PICARD" v1.0 to the path
EEGLAB: adding "PrepPipeline" v0.56.0 (see >> help eegplugin_prepPipeline)
EEGLAB: adding "RELAX" v2.0.0 (see >> help eegplugin_RELAX)
EEGLAB: adding "clean_rawdata" v2.91 (see >> help eegplugin_clean_rawdata)
EEGLAB: adding "dipfit" v5.4 (see >> help eegplugin_dipfit)
EEGLAB: adding "fieldtrip-" v20231220 to the path
EEGLAB: adding "firfilt" v2.8 (see >> help eegplugin_firfilt)
EEGLAB: adding "icablinkmetrics" v3.1 (see >> help eegplugin_icablinkmetrics)
You are using the latest version of EEGLAB v2024.0.
```

PFA a sample dataset link: https://drive.google.com/file/d/1u_rXB3XE-oIQr08x8aikY2Tfs6rNvAZg/view?usp=sharing

**Comment by NeilwBailey** [comment]
Hi there

This is a quite unusual issue. It seems that the pop_chanedit function that
RELAX uses to load the electrode labels into the data does not load the
electrode labels from your .txt file containing your electrode labels. I'm
not sure why this is the case, but when I manually load the electrode
labels from that txt file (via the EEGLAB gui), then save the file, then
run RELAX on that saved file (without specifying the electrode label file -
leaving that option empty in the RELAX gui), then RELAX can effectively
clean your data.

I tried to save a few channel location files from the EEGLAB gui to enable
RELAX to load the gui without manually saving the channel location files
into your data, but none of the file formats I attempted to use worked. One
solution would be to write a script that you can run to copy the channel
locations (found in EEG.chanlocs) into all your EEG files then save those
files first. After that, you will be able to run RELAX on your data, just
leaving the channel location file unspecified in the cfg file or gui (by
leaving the field blank).

Alternatively, you could obtain a channel location file that works with the
pop_chanedit function (there must be a way to do this, so if you work it
out, please let me know and I might be able to update RELAX or the
instructions so that this issue doesn't arise for future users).

Kind regards,

Neil

**Comment by NeilwBailey** [comment]
Hi there

One additional alternative that I think might work - you could change line 130 in the RELAX_Wrapper.m script:

From: EEG=pop_chanedit(EEG,  'lookup', RELAX_cfg.caploc);

Change to: EEG=pop_chanedit(EEG,  'load', RELAX_cfg.caploc);

This seems to directly load the electrode file labels from your txt file, and seems to work, where 'lookup' does not. This could be a more simple solution than the one I mentioned above (if it works).

Kind regards,

Neil

**Comment by mitanshu7** [comment]
Dear @NeilwBailey,

I am so grateful to you for all the effort!

And yes, changing the Line 130 in RELAX_Wrapper.m script worked like a charm on the default configuration!

However, I am facing a new problem. 

When I check the MWF cleaning boxes for Brain, Eye and Muscle on the same eeg data, I see this error:

![Screenshot from 2024-07-22 20-26-37](https://github.com/user-attachments/assets/514f8ec0-43f8-4609-b4ba-f1312b38c950)

Please let me know if you have any insights for the same.

And once again I wanted to thank you for the hack!

**Comment by NeilwBailey** [comment]
The reason for this issue is that RELAX 2.0.0 calls the updated version of the MWF toolbox, rather than the original version. The updated version can be downloaded here: https://github.com/exporl/mwf-artifact-removal

Once you replace the old version of the MWF toolbox with this updated version in your EEGLAB plugins folder (and make sure it's listed on your MATLAB path when running RELAX), this issue should be resolved.

Kind regards,

Neil

**Comment by mitanshu7** [comment]
Hello @NeilwBailey,

I downloaded the plugin from the releases page instead of downloading the zip from the master branch. 

I see that you already made the modification in wiki, which I was about to suggest. 

Thank you so much for all the support!
